openapi: 3.0.0
info:
  title: "API Documentation"
  version: "1.0.0"
servers:
  - url: "http://localhost:3000"
paths:
  /clothing:
    get:
      summary: "Retrieve a list of clothing"
      responses:
        '200':
          description: "A list of clothing items"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: "Shirt"

  /clothing/create:
    post:
      summary: "Create a new clothing item"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "New Shirt"
      responses:
        '201':
          description: "Item created"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: "New Shirt"

  /clothing/delete:
    delete:
      summary: "Delete an item based on ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
      responses:
        '204':
          description: "Item deleted"

  /clothing/update:
    put:
      summary: "Update an existing item"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                name:
                  type: string
                  example: "Updated Shirt"
      responses:
        '200':
          description: "Item updated"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: "Updated Shirt"
